project_id = "rltclxpityikqxolwkgb"

[functions.generate-plan]
verify_jwt = false

[functions.analyze-food]
verify_jwt = false

[functions.ai-chat]
verify_jwt = true

[functions.automate-finances]
verify_jwt = false
